using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aarohi.Networking
{
    /// <summary>
    /// Selectively removes ONLY the IMTS report email whose hidden
    /// cleanup marker matches the marker created by MailHelpers.
    ///
    /// Nothing is deleted by subject alone.
    /// Normal Zoho emails and OTP emails are not touched.
    /// </summary>
    public static class ZohoMailCleanupService
    {
        private static readonly HttpClient _httpClient =
            new HttpClient();

        private static readonly SemaphoreSlim _metadataLock =
            new SemaphoreSlim(1, 1);

        private static string _cachedAccountId =
            string.Empty;

        private static string _cachedSentFolderId =
            string.Empty;

        // ============================================================
        // PUBLIC ENTRY POINT
        // ============================================================

        public static async Task<ZohoSentCleanupResult>
            DeleteExactSentReportAsync(
                string cleanupMarker,
                string expectedSubject,
                CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(
                    cleanupMarker))
            {
                return ZohoSentCleanupResult.Failed(
                    "Cleanup marker is empty.");
            }

            if (string.IsNullOrWhiteSpace(
                    expectedSubject))
            {
                return ZohoSentCleanupResult.Failed(
                    "Expected report subject is empty.");
            }

            try
            {
                string accountId =
                    await GetAccountIdAsync(
                        cancellationToken);

                string sentFolderId =
                    await GetSentFolderIdAsync(
                        accountId,
                        cancellationToken);

                for (int attempt = 1;
                     attempt <= ZohoApiConfiguration.CleanupMaxAttempts;
                     attempt++)
                {
                    cancellationToken
                        .ThrowIfCancellationRequested();

                    Debug.WriteLine(
                        $"ZOHO CLEANUP: Attempt {attempt}/{ZohoApiConfiguration.CleanupMaxAttempts}. Marker={cleanupMarker}");

                    IReadOnlyList<ZohoSentMessageInfo> messages =
                        await GetLatestSentMessagesAsync(
                            accountId,
                            sentFolderId,
                            cancellationToken);

                    foreach (ZohoSentMessageInfo message in messages)
                    {
                        cancellationToken
                            .ThrowIfCancellationRequested();

                        // Safety filter #1:
                        // exact report subject generated by this send.
                        if (!string.Equals(
                                message.Subject,
                                expectedSubject,
                                StringComparison.OrdinalIgnoreCase))
                        {
                            continue;
                        }

                        // Safety filter #2:
                        // only messages sent from our configured mailbox.
                        if (!string.Equals(
                                message.FromAddress,
                                ZohoApiConfiguration.SenderEmail,
                                StringComparison.OrdinalIgnoreCase))
                        {
                            continue;
                        }

                        // Safety filter #3:
                        // retrieve the actual message body and require
                        // our unique hidden marker to be present.
                        string content =
                            await GetMessageContentAsync(
                                accountId,
                                sentFolderId,
                                message.MessageId,
                                cancellationToken);

                        if (string.IsNullOrWhiteSpace(
                                content))
                        {
                            continue;
                        }

                        if (!content.Contains(
                                cleanupMarker,
                                StringComparison.Ordinal))
                        {
                            continue;
                        }

                        // This is the exact SMTP message created by this
                        // SendReportEmail call.
                        await DeleteMessageAsync(
                            accountId,
                            sentFolderId,
                            message.MessageId,
                            cancellationToken);

                        Debug.WriteLine(
                            $"ZOHO CLEANUP: Exact IMTS Sent copy removed. MessageId={message.MessageId}");

                        return
                            ZohoSentCleanupResult
                                .DeletedSuccessfully(
                                    message.MessageId);
                    }

                    if (attempt <
                        ZohoApiConfiguration.CleanupMaxAttempts)
                    {
                        await Task.Delay(
                            ZohoApiConfiguration.CleanupRetryDelayMilliseconds,
                            cancellationToken);
                    }
                }

                return
                    ZohoSentCleanupResult
                        .NotFound();
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(
                    "ZOHO CLEANUP ERROR: " +
                    ex);

                return
                    ZohoSentCleanupResult
                        .Failed(
                            ex.Message);
            }
        }

        // ============================================================
        // ACCOUNT ID - AUTOMATIC
        // ============================================================

        private static async Task<string> GetAccountIdAsync(
            CancellationToken cancellationToken)
        {
            if (!string.IsNullOrWhiteSpace(
                    _cachedAccountId))
            {
                return _cachedAccountId;
            }

            await _metadataLock.WaitAsync(
                cancellationToken);

            try
            {
                if (!string.IsNullOrWhiteSpace(
                        _cachedAccountId))
                {
                    return _cachedAccountId;
                }

                string json =
                    await SendZohoRequestForStringAsync(
                        HttpMethod.Get,
                        $"{ZohoApiConfiguration.MailApiBaseUrl}/accounts",
                        cancellationToken);

                using JsonDocument document =
                    JsonDocument.Parse(json);

                EnsureZohoSuccess(
                    document.RootElement,
                    json);

                if (!document.RootElement.TryGetProperty(
                        "data",
                        out JsonElement data) ||
                    data.ValueKind !=
                        JsonValueKind.Array)
                {
                    throw new InvalidOperationException(
                        "Zoho accounts response does not contain a data array.");
                }

                foreach (JsonElement account in
                         data.EnumerateArray())
                {
                    string accountId =
                        GetJsonString(
                            account,
                            "accountId");

                    string primaryEmail =
                        GetJsonString(
                            account,
                            "primaryEmailAddress");

                    string mailboxAddress =
                        GetJsonString(
                            account,
                            "mailboxAddress");

                    bool emailMatches =
                        string.Equals(
                            primaryEmail,
                            ZohoApiConfiguration.SenderEmail,
                            StringComparison.OrdinalIgnoreCase) ||
                        string.Equals(
                            mailboxAddress,
                            ZohoApiConfiguration.SenderEmail,
                            StringComparison.OrdinalIgnoreCase);

                    if (emailMatches &&
                        !string.IsNullOrWhiteSpace(
                            accountId))
                    {
                        _cachedAccountId =
                            accountId;

                        Debug.WriteLine(
                            $"ZOHO API: AccountId discovered automatically: {_cachedAccountId}");

                        return
                            _cachedAccountId;
                    }
                }

                throw new InvalidOperationException(
                    $"Zoho account for '{ZohoApiConfiguration.SenderEmail}' was not found.");
            }
            finally
            {
                _metadataLock.Release();
            }
        }

        // ============================================================
        // SENT FOLDER ID - AUTOMATIC
        // ============================================================

        private static async Task<string> GetSentFolderIdAsync(
            string accountId,
            CancellationToken cancellationToken)
        {
            if (!string.IsNullOrWhiteSpace(
                    _cachedSentFolderId))
            {
                return _cachedSentFolderId;
            }

            await _metadataLock.WaitAsync(
                cancellationToken);

            try
            {
                if (!string.IsNullOrWhiteSpace(
                        _cachedSentFolderId))
                {
                    return _cachedSentFolderId;
                }

                string json =
                    await SendZohoRequestForStringAsync(
                        HttpMethod.Get,
                        $"{ZohoApiConfiguration.MailApiBaseUrl}/accounts/{Uri.EscapeDataString(accountId)}/folders",
                        cancellationToken);

                using JsonDocument document =
                    JsonDocument.Parse(json);

                EnsureZohoSuccess(
                    document.RootElement,
                    json);

                if (!document.RootElement.TryGetProperty(
                        "data",
                        out JsonElement data) ||
                    data.ValueKind !=
                        JsonValueKind.Array)
                {
                    throw new InvalidOperationException(
                        "Zoho folders response does not contain a data array.");
                }

                foreach (JsonElement folder in
                         data.EnumerateArray())
                {
                    string folderId =
                        GetJsonString(
                            folder,
                            "folderId");

                    string folderName =
                        GetJsonString(
                            folder,
                            "folderName");

                    string folderType =
                        GetJsonString(
                            folder,
                            "folderType");

                    bool isSent =
                        string.Equals(
                            folderName,
                            "Sent",
                            StringComparison.OrdinalIgnoreCase) ||
                        string.Equals(
                            folderType,
                            "Sent",
                            StringComparison.OrdinalIgnoreCase);

                    if (isSent &&
                        !string.IsNullOrWhiteSpace(
                            folderId))
                    {
                        _cachedSentFolderId =
                            folderId;

                        Debug.WriteLine(
                            $"ZOHO API: Sent folder discovered automatically: {_cachedSentFolderId}");

                        return
                            _cachedSentFolderId;
                    }
                }

                throw new InvalidOperationException(
                    "Zoho Sent folder was not found.");
            }
            finally
            {
                _metadataLock.Release();
            }
        }

        // ============================================================
        // LIST NEWEST SENT MESSAGES
        // ============================================================

        private static async Task<IReadOnlyList<ZohoSentMessageInfo>>
            GetLatestSentMessagesAsync(
                string accountId,
                string sentFolderId,
                CancellationToken cancellationToken)
        {
            string url =
                $"{ZohoApiConfiguration.MailApiBaseUrl}/accounts/{Uri.EscapeDataString(accountId)}/messages/view" +
                $"?folderId={Uri.EscapeDataString(sentFolderId)}" +
                "&start=1" +
                $"&limit={ZohoApiConfiguration.SentMessagesToInspect}" +
                "&sortBy=date" +
                "&sortorder=false" +
                "&includeto=true";

            string json =
                await SendZohoRequestForStringAsync(
                    HttpMethod.Get,
                    url,
                    cancellationToken);

            using JsonDocument document =
                JsonDocument.Parse(json);

            EnsureZohoSuccess(
                document.RootElement,
                json);

            List<ZohoSentMessageInfo> messages =
                new List<ZohoSentMessageInfo>();

            if (!document.RootElement.TryGetProperty(
                    "data",
                    out JsonElement data) ||
                data.ValueKind !=
                    JsonValueKind.Array)
            {
                return messages;
            }

            foreach (JsonElement item in
                     data.EnumerateArray())
            {
                string messageId =
                    GetJsonString(
                        item,
                        "messageId");

                if (string.IsNullOrWhiteSpace(
                        messageId))
                {
                    continue;
                }

                messages.Add(
                    new ZohoSentMessageInfo
                    {
                        MessageId =
                            messageId,

                        Subject =
                            GetJsonString(
                                item,
                                "subject"),

                        FromAddress =
                            GetJsonString(
                                item,
                                "fromAddress"),

                        ToAddress =
                            GetJsonString(
                                item,
                                "toAddress")
                    });
            }

            return messages;
        }

        // ============================================================
        // GET CONTENT OF ONE MESSAGE
        // ============================================================

        private static async Task<string> GetMessageContentAsync(
            string accountId,
            string folderId,
            string messageId,
            CancellationToken cancellationToken)
        {
            string url =
                $"{ZohoApiConfiguration.MailApiBaseUrl}/accounts/{Uri.EscapeDataString(accountId)}" +
                $"/folders/{Uri.EscapeDataString(folderId)}" +
                $"/messages/{Uri.EscapeDataString(messageId)}" +
                "/content";

            string json =
                await SendZohoRequestForStringAsync(
                    HttpMethod.Get,
                    url,
                    cancellationToken);

            using JsonDocument document =
                JsonDocument.Parse(json);

            EnsureZohoSuccess(
                document.RootElement,
                json);

            if (!document.RootElement.TryGetProperty(
                    "data",
                    out JsonElement data) ||
                data.ValueKind !=
                    JsonValueKind.Object)
            {
                return string.Empty;
            }

            return GetJsonString(
                data,
                "content");
        }

        // ============================================================
        // DELETE / MOVE TO TRASH
        // ============================================================

        private static async Task DeleteMessageAsync(
            string accountId,
            string folderId,
            string messageId,
            CancellationToken cancellationToken)
        {
            string expunge =
                ZohoApiConfiguration.ExpungePermanently
                    ? "true"
                    : "false";

            string url =
                $"{ZohoApiConfiguration.MailApiBaseUrl}/accounts/{Uri.EscapeDataString(accountId)}" +
                $"/folders/{Uri.EscapeDataString(folderId)}" +
                $"/messages/{Uri.EscapeDataString(messageId)}" +
                $"?expunge={expunge}";

            string json =
                await SendZohoRequestForStringAsync(
                    HttpMethod.Delete,
                    url,
                    cancellationToken);

            using JsonDocument document =
                JsonDocument.Parse(json);

            EnsureZohoSuccess(
                document.RootElement,
                json);
        }

        // ============================================================
        // HTTP HELPER WITH AUTOMATIC TOKEN REFRESH
        // ============================================================

        private static async Task<string> SendZohoRequestForStringAsync(
            HttpMethod method,
            string url,
            CancellationToken cancellationToken)
        {
            string accessToken =
                await ZohoOAuthService
                    .GetAccessTokenAsync(
                        cancellationToken);

            using HttpResponseMessage response =
                await SendOnceAsync(
                    method,
                    url,
                    accessToken,
                    cancellationToken);

            // If Zoho says token expired/invalid, refresh once
            // automatically and retry the exact same API call.
            if (response.StatusCode ==
                HttpStatusCode.Unauthorized)
            {
                response.Dispose();

                ZohoOAuthService
                    .InvalidateCachedAccessToken();

                string newAccessToken =
                    await ZohoOAuthService
                        .GetAccessTokenAsync(
                            cancellationToken);

                using HttpResponseMessage retryResponse =
                    await SendOnceAsync(
                        method,
                        url,
                        newAccessToken,
                        cancellationToken);

                string retryJson =
                    await retryResponse.Content
                        .ReadAsStringAsync(
                            cancellationToken);

                if (!retryResponse.IsSuccessStatusCode)
                {
                    throw new InvalidOperationException(
                        $"Zoho Mail API failed. HTTP {(int)retryResponse.StatusCode}. Response: {retryJson}");
                }

                return retryJson;
            }

            string json =
                await response.Content
                    .ReadAsStringAsync(
                        cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                throw new InvalidOperationException(
                    $"Zoho Mail API failed. HTTP {(int)response.StatusCode}. Response: {json}");
            }

            return json;
        }

        private static async Task<HttpResponseMessage> SendOnceAsync(
            HttpMethod method,
            string url,
            string accessToken,
            CancellationToken cancellationToken)
        {
            using HttpRequestMessage request =
                new HttpRequestMessage(
                    method,
                    url);

            request.Headers.Accept.Add(
                new MediaTypeWithQualityHeaderValue(
                    "application/json"));

            request.Headers.TryAddWithoutValidation(
                "Authorization",
                $"Zoho-oauthtoken {accessToken}");

            return await _httpClient.SendAsync(
                request,
                cancellationToken);
        }

        // ============================================================
        // RESPONSE HELPERS
        // ============================================================

        private static void EnsureZohoSuccess(
            JsonElement root,
            string rawJson)
        {
            if (!root.TryGetProperty(
                    "status",
                    out JsonElement status))
            {
                throw new InvalidOperationException(
                    $"Zoho response does not contain status. Response: {rawJson}");
            }

            int code =
                0;

            if (status.TryGetProperty(
                    "code",
                    out JsonElement codeElement))
            {
                if (codeElement.ValueKind ==
                    JsonValueKind.Number)
                {
                    codeElement.TryGetInt32(
                        out code);
                }
                else if (codeElement.ValueKind ==
                         JsonValueKind.String)
                {
                    int.TryParse(
                        codeElement.GetString(),
                        out code);
                }
            }

            if (code != 200)
            {
                string description =
                    GetJsonString(
                        status,
                        "description");

                throw new InvalidOperationException(
                    $"Zoho API returned code {code}: {description}. Response: {rawJson}");
            }
        }

        private static string GetJsonString(
            JsonElement element,
            string propertyName)
        {
            if (!element.TryGetProperty(
                    propertyName,
                    out JsonElement value))
            {
                return string.Empty;
            }

            if (value.ValueKind ==
                JsonValueKind.Null)
            {
                return string.Empty;
            }

            return value.ToString()
                ?.Trim()
                ?? string.Empty;
        }

        private sealed class ZohoSentMessageInfo
        {
            public string MessageId { get; set; } =
                string.Empty;

            public string Subject { get; set; } =
                string.Empty;

            public string FromAddress { get; set; } =
                string.Empty;

            public string ToAddress { get; set; } =
                string.Empty;
        }
    }
}
