<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
		<GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>
        <!-- 1. Package Identity (Essential for NuGet) -->
        <PackageId>Aarohi.Wpf.Controls</PackageId>  
        <Version>1.0.0.72</Version>
        <Authors>Aarohi Embedded Systems</Authors>
        <Company>Aarohi Embedded Systems Pvt. Ltd.</Company>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Description>A collection of highly functional, customizable, and themeable WPF UserControls designed for complex enterprise applications. Includes ExtendedDataGrid and ExtendedTextBox.</Description>
        <PackageTags>WPF;DataGrid;TextBox;UI;Controls;Theme;Aarohi</PackageTags>
        <!-- 2. Package Icon -->
        <PackageIcon>Aarohi.jpg</PackageIcon>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <!-- Dependencies -->
        <PackageReference Include="Aarohi.Designer" Version="1.0.10" />
        <PackageReference Include="Aarohi.ExtendedUI" Version="1.0.3" />
        <PackageReference Include="ncalc" Version="1.3.8" />
        <!-- 3. Corrected Image Path: Removed leading backslash -->
        <None Include="Resources\Images\Aarohi.jpg" Pack="true" PackagePath="." />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Aarohi\Aarohi.csproj" />
    </ItemGroup>
</Project>
